# General setting
show_graphs : False
# Test
test: True

# Data Creation
data:
  method: "daphnet_freezing_data"  # choose one of ["random_standard","daphnet_freezing_data"]
  # below attributes does not work when custom data is used.
  test_split: "0.2"
  number_of_samples: "2**10"  #m
  number_of_variables:  "2**6"  #n

# Experiment Inputs
maxiter: "100"
epsilon: "1e-6"

# Algorithms
solver_methods: ["appfw"] # A combination of these 3 ["asfw", "bpfw", "appfw"]
line_search_asfw:        #"golden_search"
line_search_bpfw:        #"armijo_search"









